name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx format:check
      - run: npx nx affected -t lint --parallel=3 --base=origin/main --head=origin/main
      - run: npx nx affected -t test --parallel=3 --base=origin/main --head=origin/main
      - run: npx nx affected -t build --parallel=3 --base=origin/main --head=origin/main
